source: "./"
theme: just-the-docs
search_enabled: false
logo: "/assets/logo.svg"
enable_copy_code_button: true
collections:
  assets:
    output: true
  balls:
    output: true
  caps:
    output: true
  coats:
    output: true
  fur:
    output: true
  items:
    output: true
  shoes:
    output: true